### ISSUE TITLE
Mac pkill wiki not appearing

### ISSUE THREAD

**Issue by M1kep** [rogalmic/vscode-zsh-debug#6]
Removed template as this issue pertains to the repository.

The Readme references a link to the GitHub wiki for the following:

`Read here if your mac has /usr/local/bin/pkill.`

"Here" is linking to: https://github.com/rogalmic/vscode-zsh-debug/wiki/macOS:-avoid-use-of--usr-local-bin-pkill

This link, as well as the Wiki, appears to be dead.

**Comment by texastoland** [comment]
Looks like it's supposed to be https://github.com/rogalmic/vscode-bash-debug/wiki/macOS:-avoid-use-of--usr-local-bin-pkill.

**Comment by rogalmic** [comment]
Changed the link in README, thanks for pointing that out.
